import subprocess, re, os, time

history = os.system('cat /etc/resolv.conf >> /etc/resolv.conf.history')
h_read = subprocess.run(['cat', '/etc/resolv.conf.history'], capture_output=True).stdout.decode()

cf_t = ('Cloudflare', '1.1.1.1', '1.0.0.1')
g_t = ('Google public', '8.8.8.8', '8.8.4.4')
od_t = ('OpenDNS', '208.67.222.222', '208.67.220.220')
sh_t = ('Shecan', '178.22.122.100', '185.51.200.2')
a_t = ('Azad(403)', '10.202.10.202', '10.202.10.102')
print('Welcome to DNS changer')
print("""DNS servers list:
     ________________________________________
     | DNS server name  | DNS server number |
     |--------------------------------------|
     |    Cloudflare    |       (1)         |
     |--------------------------------------|
     |      Google      |       (2)         |
     |--------------------------------------|
     |     OpenDNS      |       (3)         |
     |--------------------------------------|
     |      Shecan      |       (4)         |
     |--------------------------------------|
     |     Azad(403)    |       (5)         |
     |--------------------------------------|
     |    Default DNS   |       (d)         |
     |--------------------------------------|
     |>>>>>>>> created by D4rk $ide <<<<<<<<|
     ----------------------------------------
     """)
sd = input('select dns: ')  # 'sd' -> selected DNS

if sd == '1':
    os.system(f'echo nameserver {cf_t[1]} > /etc/resolv.conf && echo nameserver {cf_t[2]} >> /etc/resolv.conf')
elif sd == '2':
    os.system(f'echo nameserver {g_t[1]} > /etc/resolv.conf && echo nameserver {g_t[2]} >> /etc/resolv.conf')
elif sd == '3':
    os.system(f'echo nameserver {od_t[1]} > /etc/resolv.conf && echo nameserver {od_t[2]} >> /etc/resolv.conf')
elif sd == '4':
    os.system(f'echo nameserver {sh_t[1]} > /etc/resolv.conf && echo nameserver {sh_t[2]} >> /etc/resolv.conf')
elif sd == '5':
    os.system(f'echo nameserver {a_t[1]} > /etc/resolv.conf && echo nameserver {a_t[2]} >> /etc/resolv.conf')
elif sd == 'd':
    d_find = list(re.findall('# Generated by NetworkManager\nnameserver (.*)\n', h_read))
    os.system(f'echo nameserver {d_find[0]} > /etc/resolv.conf')
else:
    print('please type your dns server code.')

d_check = list(re.findall('nameserver (.*)', h_read))
udl = subprocess.run(['cat', '/etc/resolv.conf'], capture_output=True).stdout.decode()  # 'udl' -> user dns linux
udlf = tuple(re.findall('nameserver (.*)', udl))  # 'udlf' -> user dns linux find

if udlf == cf_t[1:]:
    print(f"You are now using the '{cf_t[0]}' DNS \nGood luck!")
    time.sleep(2)
    os.system('clear')
elif udlf == g_t[1:]:
    print(f"You are now using the '{g_t[0]}' DNS \nGood luck!")
    time.sleep(2)
    os.system('clear')
elif udlf == od_t[1:]:
    print(f"You are now using the '{od_t[0]}' DNS \nGood luck!")
    time.sleep(2)
    os.system('clear')
elif udlf == sh_t[1:]:
    print(f"You are now using the '{sh_t[0]}' DNS \nGood luck!")
    time.sleep(2)
    os.system('clear')
elif udlf == a_t[1:]:
    print(f"You are now using the '{a_t[0]}' DNS \nGood luck!")
    time.sleep(2)
    os.system('clear')
elif udlf == d_check[0]:
    print(f"Your DNS has been restored to its original state.\nGood luck!")
    time.sleep(2)
    os.system('clear')
